name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: codexlangbot

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}
        tag_with_sha: true
        tag_with_ref: true
